// This file is auto-generated by the script at script/generateImageImports.ts

import A20201220 from '#images/20201220_病ん太廊.jpg'
import A20210321 from '#images/20210321_病ん太廊.jpg'
import A20210411 from '#images/20210411_病ん太廊.jpg'
import A20210514 from '#images/20210514_病ん太廊.jpg'
import A20210706 from '#images/20210706_温野りょく.jpg'
import A20210909JUNGLE from '#images/20210909_JUNGLE.jpg'
import A20210918 from '#images/20210918_病ん太廊.jpg'
import A20211102 from '#images/20211102_温野りょく.jpg'
import A20211113 from '#images/20211113_病ん太廊.jpg'
import A20211114AsuMi from '#images/20211114_AsuMi.jpg'
import A20211209PUKARA from '#images/20211209_PUKARA.jpg'
import A20211209 from '#images/20211209_病ん太廊.jpg'
import A20211225 from '#images/20211225_アータ.jpg'
import A20220227UZ from '#images/20220227_U枝Z狼.jpg'
import A20220326 from '#images/20220326_温野りょく.jpg'
import A20220427 from '#images/20220427_病ん太廊.jpg'
import A20220429UZ from '#images/20220429_U枝Z狼.jpg'
import A20220611 from '#images/20220611_うたゆうか.jpg'
import A20220622JUNGLE from '#images/20220622_JUNGLE.jpg'
import A20220712 from '#images/20220712_けーえぬ.jpg'
import A20220806 from '#images/20220806_うたゆうか.jpg'
import A20220817 from '#images/20220817_紫信号.jpg'
import A20220824 from '#images/20220824_病ん太廊.jpg'
import A20220915 from '#images/20220915_七市.jpg'
import A20220922 from '#images/20220922_温野りょく.jpg'
import A20221001AsuMi from '#images/20221001_AsuMi.jpg'
import A20221014 from '#images/20221014_温野りょく.jpg'
import A20221106GSUS from '#images/20221106_GSUS.jpg'
import A20221113 from '#images/20221113_七市.jpg'
import A20221211Gisyu from '#images/20221211_Gisyu.jpg'
import A20221231 from '#images/20221231_うたゆうか.jpg'
import A20230113GSUS from '#images/20230113_GSUS.jpg'
import A20230119 from '#images/20230119_こびんびん.jpg'
import A20230129 from '#images/20230129_七市.jpg'
import A20230210 from '#images/20230210_温野りょく.jpg'
import A20230319Gisyu from '#images/20230319_Gisyu.jpg'
import A20230327 from '#images/20230327_もけ太.jpg'
import A20230405 from '#images/20230405_島どうま.jpg'
import A20230527 from '#images/20230527_病ん太廊.jpg'
import A20230603 from '#images/20230603_うたゆうか.jpg'
import A20230611 from '#images/20230611_病ん太廊.jpg'
import A20230613 from '#images/20230613_中村六翅.jpg'
import A20230617 from '#images/20230617_温野りょく.jpg'
import A20230629 from '#images/20230629_七市.jpg'
import A20230702 from '#images/20230702_アータ.jpg'
import A20230706 from '#images/20230706_七市.jpg'
import A20230808 from '#images/20230808_中村六翅.jpg'
import A20230830 from '#images/20230830_七市.jpg'
import A20230912 from '#images/20230912_温野りょく.jpg'
import A20230914 from '#images/20230914_もけ太.jpg'
import A20230917 from '#images/20230917.jpg'
import A20230924 from '#images/20230924.jpg'
import A20231005 from '#images/20231005_ぐれます.jpg'
import A20231006 from '#images/20231006_うたゆうか.jpg'
import A202310181stAlbumRelease from '#images/20231018_1st Album Release.jpg'
import A20231031 from '#images/20231031_七市.jpg'
import A20231109YYDAP from '#images/20231109_YYDAP.jpg'
import A20231117Happy4thAnniv from '#images/20231117_Happy 4th Anniv..jpg'
import A20231204 from '#images/20231204_温野りょく.jpg'
import A20231215parallelcanvasII from '#images/20231215_parallel canvas II.jpg'
import A20231227 from '#images/20231227_そーだみず.jpg'
import A20231231 from '#images/20231231_流し満貫.jpg'
import A20240113VWPII from '#images/20240113_V.W.P 現象II.jpg'
import A20240114 from '#images/20240114_七市.jpg'
import A20240223AOS from '#images/20240223_AOS.jpg'
import A20240225 from '#images/20240225.jpg'
import A20240405 from '#images/20240405_七市.jpg'
import A20240406 from '#images/20240406_どれい.jpg'
import A20240408 from '#images/20240408_病ん太廊.jpg'
import A20240409 from '#images/20240409_雪国裕.jpg'
import A20240410 from '#images/20240410.jpg'
import A20240421Gisyu from '#images/20240421_Gisyu.jpg'
import A20240423 from '#images/20240423.jpg'
import A20240513 from '#images/20240513.jpg'
import A20240515 from '#images/20240515_七市.jpg'
import A20240519 from '#images/20240519_たれぞう.jpg'
import A20240620 from '#images/20240620_どれい.jpg'
import A20240725AOS from '#images/20240725_AOS.jpg'
import A20240726Welcomeparty from '#images/20240726_Welcome party.jpg'
import A20240729 from '#images/20240729.jpg'

export const imageImports = {
  '20201220_病ん太廊': A20201220,
  '20210321_病ん太廊': A20210321,
  '20210411_病ん太廊': A20210411,
  '20210514_病ん太廊': A20210514,
  '20210706_温野りょく': A20210706,
  '20210909_JUNGLE': A20210909JUNGLE,
  '20210918_病ん太廊': A20210918,
  '20211102_温野りょく': A20211102,
  '20211113_病ん太廊': A20211113,
  '20211114_AsuMi': A20211114AsuMi,
  '20211209_PUKARA': A20211209PUKARA,
  '20211209_病ん太廊': A20211209,
  '20211225_アータ': A20211225,
  '20220227_U枝Z狼': A20220227UZ,
  '20220326_温野りょく': A20220326,
  '20220427_病ん太廊': A20220427,
  '20220429_U枝Z狼': A20220429UZ,
  '20220611_うたゆうか': A20220611,
  '20220622_JUNGLE': A20220622JUNGLE,
  '20220712_けーえぬ': A20220712,
  '20220806_うたゆうか': A20220806,
  '20220817_紫信号': A20220817,
  '20220824_病ん太廊': A20220824,
  '20220915_七市': A20220915,
  '20220922_温野りょく': A20220922,
  '20221001_AsuMi': A20221001AsuMi,
  '20221014_温野りょく': A20221014,
  '20221106_GSUS': A20221106GSUS,
  '20221113_七市': A20221113,
  '20221211_Gisyu': A20221211Gisyu,
  '20221231_うたゆうか': A20221231,
  '20230113_GSUS': A20230113GSUS,
  '20230119_こびんびん': A20230119,
  '20230129_七市': A20230129,
  '20230210_温野りょく': A20230210,
  '20230319_Gisyu': A20230319Gisyu,
  '20230327_もけ太': A20230327,
  '20230405_島どうま': A20230405,
  '20230527_病ん太廊': A20230527,
  '20230603_うたゆうか': A20230603,
  '20230611_病ん太廊': A20230611,
  '20230613_中村六翅': A20230613,
  '20230617_温野りょく': A20230617,
  '20230629_七市': A20230629,
  '20230702_アータ': A20230702,
  '20230706_七市': A20230706,
  '20230808_中村六翅': A20230808,
  '20230830_七市': A20230830,
  '20230912_温野りょく': A20230912,
  '20230914_もけ太': A20230914,
  '20230917': A20230917,
  '20230924': A20230924,
  '20231005_ぐれます': A20231005,
  '20231006_うたゆうか': A20231006,
  '20231018_1st Album Release': A202310181stAlbumRelease,
  '20231031_七市': A20231031,
  '20231109_YYDAP': A20231109YYDAP,
  '20231117_Happy 4th Anniv.': A20231117Happy4thAnniv,
  '20231204_温野りょく': A20231204,
  '20231215_parallel canvas II': A20231215parallelcanvasII,
  '20231227_そーだみず': A20231227,
  '20231231_流し満貫': A20231231,
  '20240113_V.W.P 現象II': A20240113VWPII,
  '20240114_七市': A20240114,
  '20240223_AOS': A20240223AOS,
  '20240225': A20240225,
  '20240405_七市': A20240405,
  '20240406_どれい': A20240406,
  '20240408_病ん太廊': A20240408,
  '20240409_雪国裕': A20240409,
  '20240410': A20240410,
  '20240421_Gisyu': A20240421Gisyu,
  '20240423': A20240423,
  '20240513': A20240513,
  '20240515_七市': A20240515,
  '20240519_たれぞう': A20240519,
  '20240620_どれい': A20240620,
  '20240725_AOS': A20240725AOS,
  '20240726_Welcome party': A20240726Welcomeparty,
  '20240729': A20240729,
}
