// This file is auto-generated by the script at script/generateImageImports.ts
// !!! DO NOT EDIT !!!
import A20201220 from '#images/webp/20201220_病ん太廊.webp'
import A20210321 from '#images/webp/20210321_病ん太廊.webp'
import A20210411 from '#images/webp/20210411_病ん太廊.webp'
import A20210514 from '#images/webp/20210514_病ん太廊.webp'
import A20210706 from '#images/webp/20210706_温野りょく.webp'
import A20210909 from '#images/webp/20210909_JUNGLE.webp'
import A20210918 from '#images/webp/20210918_病ん太廊.webp'
import A20211102 from '#images/webp/20211102_温野りょく.webp'
import A20211113 from '#images/webp/20211113_病ん太廊.webp'
import A20211114 from '#images/webp/20211114_AsuMi.webp'
import A20211208 from '#images/webp/20211208_PUKARA.webp'
import A20211209 from '#images/webp/20211209_病ん太廊.webp'
import A20211225 from '#images/webp/20211225_アータ.webp'
import A20220227 from '#images/webp/20220227_U枝Z狼.webp'
import A20220427 from '#images/webp/20220427_病ん太廊.webp'
import A20220611 from '#images/webp/20220611_うたゆうか.webp'
import A20220712 from '#images/webp/20220712_けーえぬ.webp'
import A20220806 from '#images/webp/20220806_うたゆうか.webp'
import A20220817 from '#images/webp/20220817_紫信号.webp'
import A20220824 from '#images/webp/20220824_病ん太廊.webp'
import A20220915 from '#images/webp/20220915_七市.webp'
import A20220922 from '#images/webp/20220922_温野りょく.webp'
import A20221106 from '#images/webp/20221106_GSUS.webp'
import A20221113 from '#images/webp/20221113_七市.webp'
import A20221211 from '#images/webp/20221211_Gisyu.webp'
import A20230113 from '#images/webp/20230113_GSUS.webp'
import A20230129 from '#images/webp/20230129_七市.webp'
import A20230210 from '#images/webp/20230210_温野りょく.webp'
import A20230327 from '#images/webp/20230327_もけ太.webp'
import A20230405 from '#images/webp/20230405_島どうま.webp'
import A20230527 from '#images/webp/20230527_病ん太廊.webp'
import A20230603 from '#images/webp/20230603_うたゆうか.webp'
import A20230613 from '#images/webp/20230613_中村六翅.webp'
import A20230617 from '#images/webp/20230617_温野りょく.webp'
import A20230629 from '#images/webp/20230629_七市.webp'
import A20230702 from '#images/webp/20230702_アータ.webp'
import A20230706 from '#images/webp/20230706_七市.webp'
import A20230808 from '#images/webp/20230808_中村六翅.webp'
import A20230830 from '#images/webp/20230830_七市.webp'
import A20230912 from '#images/webp/20230912_温野りょく.webp'
import A20230914 from '#images/webp/20230914_もけ太.webp'
import A20230917 from '#images/webp/20230917.webp'
import A20230924 from '#images/webp/20230924.webp'
import A20231006 from '#images/webp/20231006_うたゆうか.webp'
import A20231018 from '#images/webp/20231018.webp'
import A20231031 from '#images/webp/20231031_七市.webp'
import A20231109 from '#images/webp/20231109_YYDAP.webp'
import A20231117 from '#images/webp/20231117.webp'
import A20231204 from '#images/webp/20231204_温野りょく.webp'
import A20231215 from '#images/webp/20231215.webp'
import A20231231 from '#images/webp/20231231_流し満貫.webp'
import A20240113 from '#images/webp/20240113.webp'
import A20240114 from '#images/webp/20240114_七市.webp'
import A20240223 from '#images/webp/20240223_AOS.webp'
import A20240225 from '#images/webp/20240225.webp'
import A20240405 from '#images/webp/20240405_七市.webp'
import A20240406 from '#images/webp/20240406_どれい.webp'
import A20240409 from '#images/webp/20240409_雪国裕.webp'
import A20240410 from '#images/webp/20240410.webp'
import A20240421A from '#images/webp/20240421_Gisyu (part 1).webp'
import A20240421B from '#images/webp/20240421_Gisyu (part 2).webp'
import A20240423 from '#images/webp/20240423.webp'
import A20240513 from '#images/webp/20240513.webp'
import A20240515 from '#images/webp/20240515_七市.webp'
import A20240620 from '#images/webp/20240620_どれい.webp'
import A20240725 from '#images/webp/20240725_AOS.webp'
import A20240726 from '#images/webp/20240726.webp'
import A20240729 from '#images/webp/20240729.webp'
import A20240814 from '#images/webp/20240814.webp'
import A20240816 from '#images/webp/20240816.webp'
import A20240819A from '#images/webp/20240819_Q (part 1).webp'
import A20240819B from '#images/webp/20240819_Q (part 2).webp'
import A20240906 from '#images/webp/20240906_七市.webp'
import A20240918 from '#images/webp/20240918_AsuMi.webp'
import A20241027A from '#images/webp/20241027_Q (part 1).webp'
import A20241027B from '#images/webp/20241027_Q (part 2).webp'
import A20241028 from '#images/webp/20241028_アータ.webp'
import A20241031 from '#images/webp/20241031_温野りょく.webp'
import A20241126 from '#images/webp/20241126.webp'
import A20241130 from '#images/webp/20241130_七市.webp'
import A20241203 from '#images/webp/20241203.webp'
import A20241208 from '#images/webp/20241208.webp'
import A20241223 from '#images/webp/20241223_中村六翅.webp'
import A20241230A from '#images/webp/20241230_Q (part 1).webp'
import A20241230B from '#images/webp/20241230_Q (part 2).webp'
import A20241231 from '#images/webp/20241231_七市.webp'
import A20250117 from '#images/webp/20250117.webp'
import A20250124A from '#images/webp/20250124.webp'
import A20250124B from '#images/webp/20250124_中村六翅.webp'
import A20250205 from '#images/webp/20250205.webp'
import A20250206 from '#images/webp/20250206_温野りょく.webp'
import A20250225 from '#images/webp/20250225_七市.webp'
import A20250302A from '#images/webp/20250302_Q (part 1).webp'
import A20250302B from '#images/webp/20250302_Q (part 2).webp'
import A20250320 from '#images/webp/20250320_中村六翅.webp'
import A20250322 from '#images/webp/20250322.webp'
import A20250403 from '#images/webp/20250403_七市.webp'

export const imageImports = {
  '20201220_病ん太廊': A20201220,
  '20210321_病ん太廊': A20210321,
  '20210411_病ん太廊': A20210411,
  '20210514_病ん太廊': A20210514,
  '20210706_温野りょく': A20210706,
  '20210909_JUNGLE': A20210909,
  '20210918_病ん太廊': A20210918,
  '20211102_温野りょく': A20211102,
  '20211113_病ん太廊': A20211113,
  '20211114_AsuMi': A20211114,
  '20211208_PUKARA': A20211208,
  '20211209_病ん太廊': A20211209,
  '20211225_アータ': A20211225,
  '20220227_U枝Z狼': A20220227,
  '20220427_病ん太廊': A20220427,
  '20220611_うたゆうか': A20220611,
  '20220712_けーえぬ': A20220712,
  '20220806_うたゆうか': A20220806,
  '20220817_紫信号': A20220817,
  '20220824_病ん太廊': A20220824,
  '20220915_七市': A20220915,
  '20220922_温野りょく': A20220922,
  '20221106_GSUS': A20221106,
  '20221113_七市': A20221113,
  '20221211_Gisyu': A20221211,
  '20230113_GSUS': A20230113,
  '20230129_七市': A20230129,
  '20230210_温野りょく': A20230210,
  '20230327_もけ太': A20230327,
  '20230405_島どうま': A20230405,
  '20230527_病ん太廊': A20230527,
  '20230603_うたゆうか': A20230603,
  '20230613_中村六翅': A20230613,
  '20230617_温野りょく': A20230617,
  '20230629_七市': A20230629,
  '20230702_アータ': A20230702,
  '20230706_七市': A20230706,
  '20230808_中村六翅': A20230808,
  '20230830_七市': A20230830,
  '20230912_温野りょく': A20230912,
  '20230914_もけ太': A20230914,
  '20230917': A20230917,
  '20230924': A20230924,
  '20231006_うたゆうか': A20231006,
  '20231018': A20231018,
  '20231031_七市': A20231031,
  '20231109_YYDAP': A20231109,
  '20231117': A20231117,
  '20231204_温野りょく': A20231204,
  '20231215': A20231215,
  '20231231_流し満貫': A20231231,
  '20240113': A20240113,
  '20240114_七市': A20240114,
  '20240223_AOS': A20240223,
  '20240225': A20240225,
  '20240405_七市': A20240405,
  '20240406_どれい': A20240406,
  '20240409_雪国裕': A20240409,
  '20240410': A20240410,
  '20240421_Gisyu (part 1)': A20240421A,
  '20240421_Gisyu (part 2)': A20240421B,
  '20240423': A20240423,
  '20240513': A20240513,
  '20240515_七市': A20240515,
  '20240620_どれい': A20240620,
  '20240725_AOS': A20240725,
  '20240726': A20240726,
  '20240729': A20240729,
  '20240814': A20240814,
  '20240816': A20240816,
  '20240819_Q (part 1)': A20240819A,
  '20240819_Q (part 2)': A20240819B,
  '20240906_七市': A20240906,
  '20240918_AsuMi': A20240918,
  '20241027_Q (part 1)': A20241027A,
  '20241027_Q (part 2)': A20241027B,
  '20241028_アータ': A20241028,
  '20241031_温野りょく': A20241031,
  '20241126': A20241126,
  '20241130_七市': A20241130,
  '20241203': A20241203,
  '20241208': A20241208,
  '20241223_中村六翅': A20241223,
  '20241230_Q (part 1)': A20241230A,
  '20241230_Q (part 2)': A20241230B,
  '20241231_七市': A20241231,
  '20250117': A20250117,
  '20250124': A20250124A,
  '20250124_中村六翅': A20250124B,
  '20250205': A20250205,
  '20250206_温野りょく': A20250206,
  '20250225_七市': A20250225,
  '20250302_Q (part 1)': A20250302A,
  '20250302_Q (part 2)': A20250302B,
  '20250320_中村六翅': A20250320,
  '20250322': A20250322,
  '20250403_七市': A20250403,
}
