// scripts/generateBlurhash.ts

import { encode } from 'blurhash'
import { loadImage, createCanvas } from 'canvas'
import * as fs from 'fs'
import * as path from 'path'

const imagesDir = path.resolve(__dirname, '../public/images') // Adjust this path to match your directory structure

const generateBlurhash = async (imagePath: string): Promise<string> => {
  const image = await loadImage(imagePath)
  const canvas = createCanvas(image.width, image.height)
  const context = canvas.getContext('2d')
  context.drawImage(image, 0, 0)
  const imageData = context.getImageData(0, 0, canvas.width, canvas.height)
  return encode(imageData.data, imageData.width, imageData.height, 4, 4)
}

const generateBlurhashForAllImages = async (): Promise<void> => {
  const dirs = fs
    .readdirSync(imagesDir, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name)

  let existingBlurhashes: { [key: string]: string } = {}
  const existingDataPath = path.resolve(__dirname, '../data/blurhashes.ts')

  if (fs.existsSync(existingDataPath)) {
    const existingData = fs.readFileSync(existingDataPath, 'utf-8')
    const match = existingData.match(/export const blurhashes = (\{[^}]+\})/)
    if (match) {
      existingBlurhashes = JSON.parse(match[1])
    }
  }

  const blurhashes: { [key: string]: string } = { ...existingBlurhashes }
  let processedCount = 0

  for (const dir of dirs) {
    const files = fs.readdirSync(path.join(imagesDir, dir))
    for (const file of files) {
      const key = `${dir}/${file}`
      if (blurhashes[key]) {
        console.log(`Skipping existing entry: ${key}`)
        continue // Skip this image if it's already been processed
      }
      const imagePath = path.join(imagesDir, dir, file)
      const blurhash = await generateBlurhash(imagePath)
      blurhashes[key] = blurhash
      processedCount++
      console.log(`Processed ${processedCount} images...`)
    }
  }

  const output = `
// This file is generated by the generateBlurhash script. Do not edit manually.
export const blurhashes = ${JSON.stringify(blurhashes, null, 2)};
`

  fs.writeFileSync(existingDataPath, output)
}

generateBlurhashForAllImages()
